### ISSUE TITLE
error while getting the deps

### ISSUE THREAD

**Issue by bsr203** [sogko/todomvc-relay-go#1]
Hi got an error while getting the deps

```
todomvc-relay-go ❯❯❯ go get -v ./...                               master
github.com/sogko/graphql-go-handler (download)
github.com/chris-ramon/graphql-go (download)
github.com/gorilla/schema (download)
github.com/unrolled/render (download)
github.com/sogko/todomvc-relay-go (download)
github.com/sogko/graphql-relay-go (download)
github.com/kr/pretty (download)
github.com/kr/text (download)
src/github.com/kr/text/mc/mc.go:13:2: cannot find package "github.com/kr/pty" in any of:
    /usr/local/go/src/github.com/kr/pty (from $GOROOT)
    /Users/bsr/Work/Github/todomvc-relay-go/src/github.com/kr/pty (from $GOPATH)
```

```
 go version                                ⏎ master ◼
go version go1.5.1 darwin/amd64

```

getting the package separately solved it

```
 go get github.com/kr/pt

```

hadn't work with go for sometime and not sure anything to do with my GOPATH

**Comment by sogko** [comment]
Hi @bsr203 , thanks for trying out the project and sharing your experience, appreciate it 👍🏻

I've looked into reproducing the error and I can't get it to manifest itself though. 
Quick search does show others tripping over `go get`-ing `github.com/kr/pretty`, Though I'm not quite sure why.

Probably I was being overzealous with that `go get -v ./...` command, resulting `go get` to get dependencies for subdirectories.
(Background: `github.com/kr/pretty` is being used in a testutil for `graphql-go`, not really used by the main packages)

`go get -v` should be sufficient, I believe.

Can I ask from you a favour to see, if you delete those downloaded packages and try `go get -v ./...` or `go get -v`,  would the error manifests again consistently?

If not, the workaround you provided would be sufficient enough

```
go get github.com/kr/pty
```

Thanks again for your time!

**Comment by bsr203** [comment]
It did work

```
~/W/G/todomvc-relay-go ❯❯❯ export GOPATH=`pwd`                                                                                                   master ◼
~/W/G/todomvc-relay-go ❯❯❯ go get -v                                                                                                             master ◼
github.com/sogko/graphql-go-handler (download)
github.com/chris-ramon/graphql-go (download)
github.com/gorilla/schema (download)
github.com/unrolled/render (download)
github.com/sogko/todomvc-relay-go (download)
github.com/sogko/graphql-relay-go (download)
go install: no install location for directory /Users/bsr/Work/Github/todomvc-relay-go outside GOPATH
    For more details see: go help gopath

npm start                                                                                                             master ◼

> todomvc-relay-go@0.1.0 start /Users/bsr/Work/Github/todomvc-relay-go
> go run graphql.go & babel-node ./server.js

App is now running on http://localhost:3000
2015/10/11 12:08:52 GraphQL server starting up on http://localhost:8080
```

thanks for your response and great work on this project. 

one another note. when I tried the demo, if I delete a todo item (by the x on the right) it doesn't clear it from the UI. I am still exploring and come up with some debug info, but if you already noticed let me know.

thanks again. bsr

**Comment by sogko** [comment]
Yeah I remember noticing that too. I assumed it was related to [an existing issue with the original TodoMVC implementation from Facebook's repo.](https://github.com/facebook/relay/issues/408)

Seems like there have been an update to the [TodoMVC example recently](https://github.com/facebook/relay/pull/436), I might update the one in this project (or I'm open to accepting PRs if anyone wants to contribute 😉, it should be a matter of simply replacing the `js` folder and updating the `schema.go`, if there are changes to `schema.js`)

Anyway, thanks again!

**Comment by bsr203** [comment]
thanks again. I will look at the FB update, but may take some time to get there as I am setting up all :-)
